// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD6j3GpIRX_-e_VLFsJdUK_WJGvVwo3fs',
    appId: '1:364946747269:web:994bd09ae01f8f08c1deec',
    messagingSenderId: '364946747269',
    projectId: 'alzheimer-4fc98',
    authDomain: 'alzheimer-4fc98.firebaseapp.com',
    storageBucket: 'alzheimer-4fc98.appspot.com',
    measurementId: 'G-Q6MG5SL1HN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4gENeQxVoPGmTMZ92SxVaCwi4BXabGsA',
    appId: '1:364946747269:android:3e4cd095b49db5a8c1deec',
    messagingSenderId: '364946747269',
    projectId: 'alzheimer-4fc98',
    storageBucket: 'alzheimer-4fc98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBicsKRN0O4oWLaBYejGQ1nIiCooHe0c4o',
    appId: '1:364946747269:ios:68125b2bb12b6036c1deec',
    messagingSenderId: '364946747269',
    projectId: 'alzheimer-4fc98',
    storageBucket: 'alzheimer-4fc98.appspot.com',
    iosClientId: '364946747269-rib6vescn59f31fbr0bsscg2ns91ck9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.alzheimer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBicsKRN0O4oWLaBYejGQ1nIiCooHe0c4o',
    appId: '1:364946747269:ios:68125b2bb12b6036c1deec',
    messagingSenderId: '364946747269',
    projectId: 'alzheimer-4fc98',
    storageBucket: 'alzheimer-4fc98.appspot.com',
    iosClientId: '364946747269-rib6vescn59f31fbr0bsscg2ns91ck9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.alzheimer',
  );
}
